import Foundation

enum PromptBank {
    static let all: [Prompt] = truths + dares + overtime

    private static func t(_ id: String, _ intensity: Intensity, _ sport: String, _ text: String) -> Prompt {
        Prompt(id: id, kind: .truth, intensity: intensity, sport: sport, text: text)
    }

    private static func d(_ id: String, _ intensity: Intensity, _ sport: String, _ text: String) -> Prompt {
        Prompt(id: id, kind: .dare, intensity: intensity, sport: sport, text: text)
    }

    private static let truths: [Prompt] = [
        t("t-r-1", .rookie, "Football", "Which football club would you never wear the jersey of, and why?"),
        t("t-r-2", .rookie, "Basketball", "Who is the most overrated basketball superstar in your opinion?"),
        t("t-r-3", .rookie, "Gym", "What is the gym exercise you secretly skip every time?"),
        t("t-r-4", .rookie, "Mindset", "Do you watch sports for the game, or just for the highlights?"),
        t("t-r-5", .rookie, "Football", "Have you ever celebrated a goal before checking if it actually counted?"),
        t("t-r-6", .rookie, "Running", "What is the longest you have ever run without stopping?"),
        t("t-r-7", .rookie, "Team", "Which teammate energy do you bring: captain, clown, or silent assassin?"),
        t("t-r-8", .rookie, "Football", "Messi or Ronaldo — and you have to defend it in one sentence."),
        t("t-r-9", .rookie, "Gym", "Have you ever taken a gym selfie and never posted it?"),
        t("t-r-10", .rookie, "Tennis", "Name a sport you pretend to understand but actually do not."),
        t("t-r-11", .rookie, "Football", "What was your most embarrassing miss in any sport?"),
        t("t-r-12", .rookie, "Basketball", "Have you ever claimed a lucky shot was 'all skill'?"),
        t("t-r-13", .rookie, "Team", "Who in this room would you least want as your goalkeeper?"),
        t("t-r-14", .rookie, "Gym", "Cardio or weights — what are you actually avoiding?"),
        t("t-r-15", .rookie, "Mindset", "Do you choke in the last minute or come alive?"),
        t("t-r-16", .rookie, "Football", "Which national team would you switch to if you could?"),
        t("t-r-17", .rookie, "Extreme", "What sport looks easy until you try it?"),
        t("t-r-18", .rookie, "Team", "Have you ever blamed the referee when it was clearly you?"),
        t("t-r-19", .rookie, "Basketball", "What is your fake injury of choice when you need a break?"),
        t("t-r-20", .rookie, "Football", "Which player’s celebration would you copy forever?"),

        t("t-p-1", .pro, "Football", "Have you ever thrown a match, even a little, to protect your ego?"),
        t("t-p-2", .pro, "Gym", "What is the number on the bar you tell people versus the number you actually lift?"),
        t("t-p-3", .pro, "Team", "Who here talks the most game and delivers the least?"),
        t("t-p-4", .pro, "Football", "Name a rival fanbase you respect even though you would never admit it online."),
        t("t-p-5", .pro, "Mindset", "What is the harshest thing a coach ever said to you that was true?"),
        t("t-p-6", .pro, "Basketball", "Have you ever hogged the ball because you did not trust your teammates?"),
        t("t-p-7", .pro, "Football", "Which World Cup or final do you still replay in your head?"),
        t("t-p-8", .pro, "Gym", "Have you ever judged someone at the gym and then failed the same exercise?"),
        t("t-p-9", .pro, "Running", "What race or time are you quietly ashamed you never hit?"),
        t("t-p-10", .pro, "Team", "If this group made a team, who is getting benched first?"),
        t("t-p-11", .pro, "Football", "Have you ever argued an offside you did not actually see?"),
        t("t-p-12", .pro, "Extreme", "What is the most dangerous sport you would still try for the story?"),
        t("t-p-13", .pro, "Mindset", "Do you play better when people are watching, or worse?"),
        t("t-p-14", .pro, "Basketball", "Which superstar’s work ethic would break you in a week?"),
        t("t-p-15", .pro, "Football", "Have you ever worn a jersey of a club you do not even support just to look cool?"),
        t("t-p-16", .pro, "Gym", "What fitness trend did you buy into and immediately regret?"),
        t("t-p-17", .pro, "Team", "Who in this room would you want taking the last penalty?"),
        t("t-p-18", .pro, "Tennis", "Name a sport you quit because your pride could not take the losses."),
        t("t-p-19", .pro, "Football", "What is your hottest, most indefensible sports take?"),
        t("t-p-20", .pro, "Mindset", "Have you ever cried after a game and pretended it was sweat or allergies?"),

        t("t-l-1", .legend, "Football", "If you had to drop one of your childhood sporting heroes, who is it and why?"),
        t("t-l-2", .legend, "Team", "Who here would crack first in extra time, and what would that look like?"),
        t("t-l-3", .legend, "Gym", "What body goal are you chasing that you have never said out loud?"),
        t("t-l-4", .legend, "Mindset", "When did you last let a teammate down, and did you own it?"),
        t("t-l-5", .legend, "Football", "Would you rather win ugly forever or play beautiful football and lose?"),
        t("t-l-6", .legend, "Basketball", "Have you ever wanted a teammate to miss so you could look like the closer?"),
        t("t-l-7", .legend, "Extreme", "What is the injury you still feel when the weather changes?"),
        t("t-l-8", .legend, "Team", "If the captaincy is a vote right now, who loses — and will you say it to their face?"),
        t("t-l-9", .legend, "Football", "Name the club or country whose fans you cannot stand, even in this room."),
        t("t-l-10", .legend, "Mindset", "Do you actually love the sport, or do you love winning more than the game?"),
        t("t-l-11", .legend, "Gym", "What excuse do you use when you skip training that even you do not believe?"),
        t("t-l-12", .legend, "Football", "Have you ever cheated in a pickup game and still bragged about the win?"),
        t("t-l-13", .legend, "Running", "What time, distance, or score still lives rent-free as unfinished business?"),
        t("t-l-14", .legend, "Team", "Who would you not pass to in a cup final, and why?"),
        t("t-l-15", .legend, "Basketball", "Is there a player you trash-talk about because they remind you of yourself?"),
        t("t-l-16", .legend, "Football", "If your career ended tomorrow, what would you regret never trying?"),
        t("t-l-17", .legend, "Mindset", "What is the most unsportsmanlike thing you have done and still do not regret?"),
        t("t-l-18", .legend, "Extreme", "Would you risk a season-ending injury for one legendary highlight?"),
        t("t-l-19", .legend, "Team", "Who in this group is the weakest under pressure? Be honest."),
        t("t-l-20", .legend, "Football", "If you could erase one loss from history, which one still stings?"),
    ]

    private static let dares: [Prompt] = [
        d("d-r-1", .rookie, "Gym", "Do 15 air squats while announcing each rep like a stadium DJ."),
        d("d-r-2", .rookie, "Football", "Give a 20-second pre-match pep talk as if this living room is Wembley."),
        d("d-r-3", .rookie, "Team", "Invent a team chant with everyone else’s names and perform it twice."),
        d("d-r-4", .rookie, "Gym", "Hold a 20-second plank and name three sports during it."),
        d("d-r-5", .rookie, "Football", "Mime taking a penalty in slow motion, including the run-up and celebration."),
        d("d-r-6", .rookie, "Basketball", "Do 10 jumping jacks, then freeze in a 'clutch shooter' pose for 5 seconds."),
        d("d-r-7", .rookie, "Mindset", "Say your sports motto like a movie trailer voice for 10 seconds."),
        d("d-r-8", .rookie, "Football", "Commentate the last 15 seconds of an imaginary World Cup final."),
        d("d-r-9", .rookie, "Gym", "Do 10 wall push-ups with perfect form. If you break form, restart."),
        d("d-r-10", .rookie, "Team", "High-five every player and give each one a ridiculous nickname."),
        d("d-r-11", .rookie, "Running", "Jog in place for 25 seconds while shouting split times."),
        d("d-r-12", .rookie, "Football", "Act out a VAR review using only hand signals and outrage."),
        d("d-r-13", .rookie, "Basketball", "Dribble an imaginary ball through your legs 8 times without laughing."),
        d("d-r-14", .rookie, "Gym", "Do 12 lunges (6 each side) and name a champion on every switch."),
        d("d-r-15", .rookie, "Football", "Celebrate like you just scored in stoppage time. Commit fully."),
        d("d-r-16", .rookie, "Team", "Pick a player and coach them for 20 seconds like you are on the sideline."),
        d("d-r-17", .rookie, "Tennis", "Mime a tennis serve, then argue with an invisible umpire."),
        d("d-r-18", .rookie, "Gym", "Do 20 standing calf raises while counting in a commentator accent."),
        d("d-r-19", .rookie, "Football", "Whistle (or hum) a match-start blast, then shout 'KICK OFF!'"),
        d("d-r-20", .rookie, "Mindset", "Give a 15-second interview as if you just won bronze and wanted gold."),

        d("d-p-1", .pro, "Gym", "Do 20 push-ups. After every 5, shout a different sport."),
        d("d-p-2", .pro, "Football", "Name 8 World Cup host countries in 20 seconds or do 10 burpees."),
        d("d-p-3", .pro, "Team", "Blindfold yourself (or close your eyes) and do 12 squats while the group counts."),
        d("d-p-4", .pro, "Basketball", "Hold a wall sit for 30 seconds and list starting-five positions."),
        d("d-p-5", .pro, "Football", "Re-enact a red-card argument with the next player as the referee."),
        d("d-p-6", .pro, "Gym", "Do 15 jump squats. If you stop, add 5 more."),
        d("d-p-7", .pro, "Running", "High knees for 20 seconds, then freeze and hold a medal-podium pose."),
        d("d-p-8", .pro, "Mindset", "Deliver a furious halftime rant using only sports clichés."),
        d("d-p-9", .pro, "Football", "Keep an imaginary ball in the air for 10 'kick-ups' using your feet and knees."),
        d("d-p-10", .pro, "Gym", "Do a 40-second plank. Smile the entire time or restart."),
        d("d-p-11", .pro, "Team", "Create a 4-move warm-up routine and make the group copy you once."),
        d("d-p-12", .pro, "Basketball", "Call play-by-play for 25 seconds of an imaginary buzzer-beater."),
        d("d-p-13", .pro, "Football", "Do 10 mountain climbers, then kiss an imaginary trophy."),
        d("d-p-14", .pro, "Gym", "Balance on one leg for 20 seconds, switch, then bow to the crowd."),
        d("d-p-15", .pro, "Extreme", "Do 8 burpees and name an extreme sport on each landing."),
        d("d-p-16", .pro, "Team", "Pick a player to 'mark' and shadow their movements for 20 seconds."),
        d("d-p-17", .pro, "Football", "Sing 10 seconds of a famous football chant, then invent one for this group."),
        d("d-p-18", .pro, "Gym", "Do 16 walking lunges across the room announcing 'championship mode'."),
        d("d-p-19", .pro, "Mindset", "Stare down the next player like a tunnel walk, then shake hands like rivals."),
        d("d-p-20", .pro, "Basketball", "Do 20 fast-feet taps and finish with a fadeaway jumper mime."),

        d("d-l-1", .legend, "Gym", "Do 25 push-ups. Break form once and the group adds 5 more."),
        d("d-l-2", .legend, "Football", "Name 10 Ballon d’Or winners in 25 seconds or hold a 45-second wall sit."),
        d("d-l-3", .legend, "Team", "Lead the whole group in 15 jumping jacks as their new captain."),
        d("d-l-4", .legend, "Gym", "Hold a wall sit for 45 seconds while answering sports questions from the group."),
        d("d-l-5", .legend, "Football", "Commentate a hat-trick in 30 seconds without repeating a word for 'goal'."),
        d("d-l-6", .legend, "Extreme", "Do 12 burpees. After the last one, roar like you just won the title."),
        d("d-l-7", .legend, "Running", "Sprint in place for 30 seconds at max effort, then take a calm 'press conference'."),
        d("d-l-8", .legend, "Mindset", "Confess your weakest sport skill, then immediately do 20 squats to 'fix it'."),
        d("d-l-9", .legend, "Gym", "Do a 50-second plank. If your hips drop, restart from 20."),
        d("d-l-10", .legend, "Football", "Take 5 imaginary penalties. The group votes save or goal after each one."),
        d("d-l-11", .legend, "Team", "Give every player a 5-second scouting report, brutally honest but fair."),
        d("d-l-12", .legend, "Basketball", "Do 30 mountain climbers, then call the game-winning play."),
        d("d-l-13", .legend, "Football", "Act out extra-time cramp, get 'treated', then sprint back on for 10 seconds."),
        d("d-l-14", .legend, "Gym", "Complete 20 jump squats. Count backwards from 20 like a shot clock."),
        d("d-l-15", .legend, "Mindset", "Do 10 slow push-ups. On each one say a fear you have in competition."),
        d("d-l-16", .legend, "Team", "Invent a last-minute tactical change and explain it with a shoe as a whiteboard."),
        d("d-l-17", .legend, "Extreme", "Hold a hollow-body or dish position for 20 seconds, then celebrate standing up."),
        d("d-l-18", .legend, "Football", "Name a starting XI from any league in 30 seconds or do 15 burpees."),
        d("d-l-19", .legend, "Gym", "Do 3 rounds of: 5 push-ups, 5 squats, 5 lunges. No rest between rounds."),
        d("d-l-20", .legend, "Team", "Crown yourself MVP in a 20-second speech, then let the group boo or cheer."),
    ]

    private static let overtime: [Prompt] = [
        t("ot-t-1", .legend, "Overtime", "If only one person in this room gets a professional contract, who deserves it?"),
        t("ot-t-2", .legend, "Overtime", "What is the sports lie you have told so many times you almost believe it?"),
        d("ot-d-1", .legend, "Overtime", "Do 30 seconds of max-effort fast feet, then immediately name 5 Olympic sports."),
        d("ot-d-2", .legend, "Overtime", "The group picks a safe exercise. You do 20 reps while they chant your name."),
        d("ot-d-3", .legend, "Overtime", "Hold a wall sit until you name 12 football clubs from 12 different countries."),
        t("ot-t-3", .legend, "Overtime", "Which defeat taught you the most — and who in this room still needs that lesson?"),
    ]
}
