import Foundation

enum PromptBank {
    static let all: [Prompt] = truths + dares + overtime

    private static func t(_ id: String, _ intensity: Intensity, _ sport: String, _ text: String) -> Prompt {
        Prompt(id: id, kind: .truth, intensity: intensity, sport: sport, text: text)
    }

    private static func d(_ id: String, _ intensity: Intensity, _ sport: String, _ text: String) -> Prompt {
        Prompt(id: id, kind: .dare, intensity: intensity, sport: sport, text: text)
    }

    private static let truths: [Prompt] = [
        t("t-r-1", .rookie, "Football", "Which football club would you never wear the jersey of, and why?"),
        t("t-r-2", .rookie, "Basketball", "Who is the most overrated basketball superstar in your opinion?"),
        t("t-r-3", .rookie, "Gym", "What is the gym exercise you secretly skip every time?"),
        t("t-r-4", .rookie, "Mindset", "Do you watch sports for the game, or just for the highlights?"),
        t("t-r-5", .rookie, "Football", "Have you ever celebrated a goal before checking if it actually counted?"),
        t("t-r-6", .rookie, "Running", "What is the longest you have ever run without stopping?"),
        t("t-r-7", .rookie, "Team", "Which teammate energy do you bring: captain, clown, or silent assassin?"),
        t("t-r-8", .rookie, "Football", "Messi or Ronaldo — and you have to defend it in one sentence."),
        t("t-r-9", .rookie, "Gym", "Have you ever taken a gym selfie and never posted it?"),
        t("t-r-10", .rookie, "Tennis", "Name a sport you pretend to understand but actually do not."),
        t("t-r-11", .rookie, "Football", "What was your most embarrassing miss in any sport?"),
        t("t-r-12", .rookie, "Basketball", "Have you ever claimed a lucky shot was 'all skill'?"),
        t("t-r-13", .rookie, "Team", "Who in this room would you least want as your goalkeeper?"),
        t("t-r-14", .rookie, "Gym", "Cardio or weights — what are you actually avoiding?"),
        t("t-r-15", .rookie, "Mindset", "Do you choke in the last minute or come alive?"),
        t("t-r-16", .rookie, "Football", "Which national team would you switch to if you could?"),
        t("t-r-17", .rookie, "Extreme", "What sport looks easy until you try it?"),
        t("t-r-18", .rookie, "Team", "Have you ever blamed the referee when it was clearly you?"),
        t("t-r-19", .rookie, "Basketball", "What is your fake injury of choice when you need a break?"),
        t("t-r-20", .rookie, "Football", "Which player’s celebration would you copy forever?"),
        t("t-r-21", .rookie, "Football", "What scoreline still makes you shake your head years later?"),
        t("t-r-22", .rookie, "Gym", "How many days a week do you claim to train versus how many you actually do?"),
        t("t-r-23", .rookie, "Basketball", "Have you ever airballed in front of people and blamed the rim?"),
        t("t-r-24", .rookie, "Running", "Have you ever walked during a 'run' and still logged it as cardio?"),
        t("t-r-25", .rookie, "Team", "Who here would you pick last in a schoolyard draft?"),
        t("t-r-26", .rookie, "Football", "Name a club anthem you secretly know every word to."),
        t("t-r-27", .rookie, "Tennis", "Have you ever called a ball out when you knew it was in?"),
        t("t-r-28", .rookie, "Mindset", "Are you a sore loser, a sore winner, or both?"),
        t("t-r-29", .rookie, "Gym", "What machine at the gym do you still not know how to use?"),
        t("t-r-30", .rookie, "Football", "Have you ever worn boots that were way too small just to look pro?"),
        t("t-r-31", .rookie, "Basketball", "Who in this room has the worst crossover?"),
        t("t-r-32", .rookie, "Team", "Do you prefer being the star or the assist king?"),
        t("t-r-33", .rookie, "Running", "What outdoor workout weather makes you instantly cancel?"),
        t("t-r-34", .rookie, "Football", "Which derby would you rather watch live once than your own team all season?"),
        t("t-r-35", .rookie, "Extreme", "Skydiving or beginner climbing — which would you try first?"),
        t("t-r-36", .rookie, "Mindset", "What sports documentary made you cry or almost cry?"),
        t("t-r-37", .rookie, "Gym", "Have you ever lied about how much you can bench?"),
        t("t-r-38", .rookie, "Football", "Name a footballer you disliked until they joined your club."),
        t("t-r-39", .rookie, "Basketball", "Have you ever practiced a celebration more than the shot?"),
        t("t-r-40", .rookie, "Team", "Who here needs the most pep talks?"),
        t("t-r-41", .rookie, "Football", "What position would you never play even in a friendly?"),
        t("t-r-42", .rookie, "Gym", "Protein shake or fries after training — be honest."),
        t("t-r-43", .rookie, "Football", "Have you ever argued about offside with zero tactical knowledge?"),
        t("t-r-44", .rookie, "Basketball", "Have you ever said 'and one' when there was clearly no foul?"),
        t("t-r-45", .rookie, "Running", "Have you ever stretched for photos and then skipped the stretch?"),
        t("t-r-46", .rookie, "Team", "Which player here would you trust with the last free kick?"),
        t("t-r-47", .rookie, "Tennis", "Name a racket sport you think is underrated."),
        t("t-r-48", .rookie, "Football", "What was the worst haircut you have seen on a footballer?"),
        t("t-r-49", .rookie, "Mindset", "Do you talk trash before you can back it up?"),
        t("t-r-50", .rookie, "Gym", "Have you ever claimed 'leg day' and then only did calves?"),
        t("t-r-51", .rookie, "Football", "Which stadium would you pay anything to visit once?"),
        t("t-r-52", .rookie, "Basketball", "Have you ever claimed you could dunk when you absolutely cannot?"),
        t("t-r-53", .rookie, "Team", "Who here would make the worst coach?"),
        t("t-r-54", .rookie, "Football", "Have you ever booed your own player?"),
        t("t-r-55", .rookie, "Extreme", "What is the wildest sports clip you have watched on repeat?"),
        t("t-r-56", .rookie, "Gym", "What fitness influencer advice did you follow once and regret?"),
        t("t-r-57", .rookie, "Football", "Name a kit color combo you refuse to wear."),
        t("t-r-58", .rookie, "Basketball", "Have you ever traveled and still blamed the defender?"),
        t("t-r-59", .rookie, "Running", "Have you ever raced someone casually and then got properly smoked?"),
        t("t-r-60", .rookie, "Team", "Who in this room has main-character energy on matchday?"),
        t("t-r-61", .rookie, "Football", "What childhood sports dream did you quietly give up?"),
        t("t-r-62", .rookie, "Mindset", "Do you need music to train or silence?"),
        t("t-r-63", .rookie, "Football", "Have you ever predicted a 5–0 and watched a 0–0?"),
        t("t-r-64", .rookie, "Gym", "What is the heaviest thing you have ever 'accidentally' dropped in public?"),
        t("t-r-65", .rookie, "Basketball", "Who would win a 1v1 between the two quietest people here?"),
        t("t-r-66", .rookie, "Team", "Friends who lose or strangers who win — who do you pick?"),
        t("t-r-67", .rookie, "Football", "What commentary catchphrase do you quote too much?"),

        t("t-p-1", .pro, "Football", "Have you ever thrown a match, even a little, to protect your ego?"),
        t("t-p-2", .pro, "Gym", "What is the number on the bar you tell people versus the number you actually lift?"),
        t("t-p-3", .pro, "Team", "Who here talks the most game and delivers the least?"),
        t("t-p-4", .pro, "Football", "Name a rival fanbase you respect even though you would never admit it online."),
        t("t-p-5", .pro, "Mindset", "What is the harshest thing a coach ever said to you that was true?"),
        t("t-p-6", .pro, "Basketball", "Have you ever hogged the ball because you did not trust your teammates?"),
        t("t-p-7", .pro, "Football", "Which World Cup or final do you still replay in your head?"),
        t("t-p-8", .pro, "Gym", "Have you ever judged someone at the gym and then failed the same exercise?"),
        t("t-p-9", .pro, "Running", "What race or time are you quietly ashamed you never hit?"),
        t("t-p-10", .pro, "Team", "If this group made a team, who is getting benched first?"),
        t("t-p-11", .pro, "Football", "Have you ever argued an offside you did not actually see?"),
        t("t-p-12", .pro, "Extreme", "What is the most dangerous sport you would still try for the story?"),
        t("t-p-13", .pro, "Mindset", "Do you play better when people are watching, or worse?"),
        t("t-p-14", .pro, "Basketball", "Which superstar’s work ethic would break you in a week?"),
        t("t-p-15", .pro, "Football", "Have you ever worn a jersey of a club you do not even support just to look cool?"),
        t("t-p-16", .pro, "Gym", "What fitness trend did you buy into and immediately regret?"),
        t("t-p-17", .pro, "Team", "Who in this room would you want taking the last penalty?"),
        t("t-p-18", .pro, "Tennis", "Name a sport you quit because your pride could not take the losses."),
        t("t-p-19", .pro, "Football", "What is your hottest, most indefensible sports take?"),
        t("t-p-20", .pro, "Mindset", "Have you ever cried after a game and pretended it was sweat or allergies?"),
        t("t-p-21", .pro, "Football", "Have you ever switched clubs in FIFA and felt weirdly guilty?"),
        t("t-p-22", .pro, "Basketball", "Have you ever taken a bad shot just to pad your highlights?"),
        t("t-p-23", .pro, "Gym", "Have you ever skipped warm-up and paid for it the next day?"),
        t("t-p-24", .pro, "Team", "Who here would crack under a hostile away crowd?"),
        t("t-p-25", .pro, "Football", "Name a manager you defended longer than you should have."),
        t("t-p-26", .pro, "Running", "Have you ever cut a route short and still posted the distance?"),
        t("t-p-27", .pro, "Mindset", "What pre-game superstition are you too embarrassed to admit?"),
        t("t-p-28", .pro, "Football", "Have you ever celebrated a rival’s own goal too hard?"),
        t("t-p-29", .pro, "Basketball", "Who in this room bricks free throws under pressure?"),
        t("t-p-30", .pro, "Gym", "What is the most you have spent on gear you barely use?"),
        t("t-p-31", .pro, "Team", "Loyalty in losing or winning by poaching talent — which are you?"),
        t("t-p-32", .pro, "Football", "Have you ever claimed VAR ruined football, then begged for it?"),
        t("t-p-33", .pro, "Extreme", "What injury scare made you rethink how hard you push?"),
        t("t-p-34", .pro, "Mindset", "Do you ghost group chats after a bad performance?"),
        t("t-p-35", .pro, "Football", "Name a player you rate who nobody else in this room likes."),
        t("t-p-36", .pro, "Basketball", "Have you ever flopped and then denied it with a straight face?"),
        t("t-p-37", .pro, "Gym", "Have you ever filmed a set and deleted it because it looked weak?"),
        t("t-p-38", .pro, "Team", "Who would you nominate as the group’s water carrier?"),
        t("t-p-39", .pro, "Football", "What transfer rumor did you believe like it was gospel?"),
        t("t-p-40", .pro, "Tennis", "Have you ever broken a racket or nearly broken something in anger?"),
        t("t-p-41", .pro, "Running", "What pace are you proud of that still is not impressive on paper?"),
        t("t-p-42", .pro, "Football", "Have you ever argued tactics with someone who clearly knew more?"),
        t("t-p-43", .pro, "Basketball", "Who here would double-team you just to annoy you?"),
        t("t-p-44", .pro, "Mindset", "What sports failure still makes your stomach drop?"),
        t("t-p-45", .pro, "Football", "Have you ever muted a group chat during a derby meltdown?"),
        t("t-p-46", .pro, "Gym", "Have you ever claimed 'I am cut' while hiding a soft belly?"),
        t("t-p-47", .pro, "Team", "If we vote for captain right now, who wins — and who should?"),
        t("t-p-48", .pro, "Football", "What is the most toxic fan behavior you have been guilty of?"),
        t("t-p-49", .pro, "Basketball", "Have you ever called for the ball and then immediately turned it over?"),
        t("t-p-50", .pro, "Extreme", "Crash hard once or never feel that adrenaline — which do you pick?"),
        t("t-p-51", .pro, "Mindset", "Do you need revenge narratives to stay motivated?"),
        t("t-p-52", .pro, "Football", "Name a club that peaked and you still act like they are contenders."),
        t("t-p-53", .pro, "Gym", "Have you ever done a PR and immediately asked someone if they saw it?"),
        t("t-p-54", .pro, "Team", "Who here would sell a teammate out for personal glory?"),
        t("t-p-55", .pro, "Football", "Have you ever walked out of a match early and missed a late winner?"),
        t("t-p-56", .pro, "Basketball", "What NBA take would get you roasted on social media?"),
        t("t-p-57", .pro, "Running", "Have you ever raced a stranger on the street without asking?"),
        t("t-p-58", .pro, "Mindset", "Are you more afraid of losing or of looking average?"),
        t("t-p-59", .pro, "Football", "Which pundit takes do you steal and present as your own?"),
        t("t-p-60", .pro, "Team", "Who would you least want marking you in a heated game?"),
        t("t-p-61", .pro, "Gym", "What body part do you train least because ego lives elsewhere?"),
        t("t-p-62", .pro, "Football", "Have you ever defended a diving player because they were on your team?"),
        t("t-p-63", .pro, "Basketball", "Have you ever claimed defense does not sell tickets — and meant it?"),
        t("t-p-64", .pro, "Football", "What childhood kit still lives in a drawer for no reason?"),
        t("t-p-65", .pro, "Team", "Who here needs a reality check about their sports IQ?"),
        t("t-p-66", .pro, "Mindset", "Have you ever quit a team because of politics, not performance?"),
        t("t-p-67", .pro, "Extreme", "What sport would your parents absolutely forbid?"),

        t("t-l-1", .legend, "Football", "If you had to drop one of your childhood sporting heroes, who is it and why?"),
        t("t-l-2", .legend, "Team", "Who here would crack first in extra time, and what would that look like?"),
        t("t-l-3", .legend, "Gym", "What body goal are you chasing that you have never said out loud?"),
        t("t-l-4", .legend, "Mindset", "When did you last let a teammate down, and did you own it?"),
        t("t-l-5", .legend, "Football", "Win ugly forever or play beautiful football and lose — pick one."),
        t("t-l-6", .legend, "Basketball", "Have you ever wanted a teammate to miss so you could look like the closer?"),
        t("t-l-7", .legend, "Extreme", "What is the injury you still feel when the weather changes?"),
        t("t-l-8", .legend, "Team", "If the captaincy is a vote right now, who loses — and will you say it to their face?"),
        t("t-l-9", .legend, "Football", "Name the club or country whose fans you cannot stand, even in this room."),
        t("t-l-10", .legend, "Mindset", "Do you actually love the sport, or do you love winning more than the game?"),
        t("t-l-11", .legend, "Gym", "What excuse do you use when you skip training that even you do not believe?"),
        t("t-l-12", .legend, "Football", "Have you ever cheated in a pickup game and still bragged about the win?"),
        t("t-l-13", .legend, "Running", "What time, distance, or score still lives rent-free as unfinished business?"),
        t("t-l-14", .legend, "Team", "Who would you not pass to in a cup final, and why?"),
        t("t-l-15", .legend, "Basketball", "Is there a player you trash-talk about because they remind you of yourself?"),
        t("t-l-16", .legend, "Football", "If your career ended tomorrow, what would you regret never trying?"),
        t("t-l-17", .legend, "Mindset", "What is the most unsportsmanlike thing you have done and still do not regret?"),
        t("t-l-18", .legend, "Extreme", "Would you risk a season-ending injury for one legendary highlight?"),
        t("t-l-19", .legend, "Team", "Who in this group is the weakest under pressure? Be honest."),
        t("t-l-20", .legend, "Football", "If you could erase one loss from history, which one still stings?"),
        t("t-l-21", .legend, "Football", "Would you take a diving penalty if it meant a trophy?"),
        t("t-l-22", .legend, "Team", "Who here would you trade away first in a fantasy draft of this room?"),
        t("t-l-23", .legend, "Gym", "What insecurity about your body shows up hardest on sports day?"),
        t("t-l-24", .legend, "Mindset", "Have you ever sabotaged someone subtly to protect your spot?"),
        t("t-l-25", .legend, "Football", "Would you rather be hated by rivals or ignored by history?"),
        t("t-l-26", .legend, "Basketball", "Have you ever iced a teammate out of a play on purpose?"),
        t("t-l-27", .legend, "Team", "Who would you trust with your sports reputation in a press room?"),
        t("t-l-28", .legend, "Football", "Name a scandal you quietly rooted for because it helped your club."),
        t("t-l-29", .legend, "Mindset", "What praise do you crave that you pretend not to need?"),
        t("t-l-30", .legend, "Gym", "Have you ever trained through pain you should have rested?"),
        t("t-l-31", .legend, "Football", "Would you move clubs for money if it meant betraying your city?"),
        t("t-l-32", .legend, "Basketball", "Have you ever taken credit for a play you barely touched?"),
        t("t-l-33", .legend, "Team", "Who here folds when the scoreline gets ugly?"),
        t("t-l-34", .legend, "Extreme", "What is the closest you have come to a real sports injury scare?"),
        t("t-l-35", .legend, "Mindset", "Do you punish yourself after losses in unhealthy ways?"),
        t("t-l-36", .legend, "Football", "Have you ever hoped a teammate got dropped so you could start?"),
        t("t-l-37", .legend, "Gym", "What number on the scale or bar still defines your self-worth?"),
        t("t-l-38", .legend, "Team", "Who would you least want as your roommate on an away trip?"),
        t("t-l-39", .legend, "Football", "Lift one trophy and retire, or play forever without silverware — pick."),
        t("t-l-40", .legend, "Basketball", "Have you ever tanked effort when the game was already lost?"),
        t("t-l-41", .legend, "Mindset", "What sports lie have you told so often it feels true?"),
        t("t-l-42", .legend, "Football", "Name a fanbase behavior you participate in and hate yourself for."),
        t("t-l-43", .legend, "Team", "Who here is secretly jealous of someone else’s sports talent?"),
        t("t-l-44", .legend, "Running", "What race result would make you question your whole identity?"),
        t("t-l-45", .legend, "Football", "Have you ever celebrated a title that felt hollow?"),
        t("t-l-46", .legend, "Gym", "Have you ever compared bodies in the locker room and felt small?"),
        t("t-l-47", .legend, "Team", "If honesty wins, who is the least clutch person here?"),
        t("t-l-48", .legend, "Basketball", "Miss the game-winner or never take the shot — which haunts you more?"),
        t("t-l-49", .legend, "Mindset", "What fear keeps you from trying a harder league or level?"),
        t("t-l-50", .legend, "Football", "Have you ever wished injury on a rival and felt bad later?"),
        t("t-l-51", .legend, "Extreme", "Would you compete hurt if the cameras were rolling?"),
        t("t-l-52", .legend, "Team", "Who would you protect in a fight, and who would you leave?"),
        t("t-l-53", .legend, "Football", "What is the meanest thing you have yelled at a screen during a match?"),
        t("t-l-54", .legend, "Gym", "What transformation story are you selling that is half fiction?"),
        t("t-l-55", .legend, "Mindset", "Have you ever ghosted a team without saying goodbye properly?"),
        t("t-l-56", .legend, "Football", "Would you take a red card to stop a certain goal?"),
        t("t-l-57", .legend, "Team", "Who here needs to hear they are not as good as they think?"),
        t("t-l-58", .legend, "Basketball", "Have you ever altered stats in your head to look better?"),
        t("t-l-59", .legend, "Football", "If this room’s loyalty was tested, who sells out first?"),
        t("t-l-60", .legend, "Mindset", "What sports memory do you rewrite when you tell the story?"),
        t("t-l-61", .legend, "Gym", "What is the darkest thought you have had after a failed PR?"),
        t("t-l-62", .legend, "Team", "Who would you ban from the group chat after a collapse?"),
        t("t-l-63", .legend, "Football", "Cult hero at a small club or squad player at a giant — pick."),
        t("t-l-64", .legend, "Extreme", "What risk would your future self beg you not to take?"),
        t("t-l-65", .legend, "Mindset", "When the lights are brightest, do you shrink or swell?"),
        t("t-l-66", .legend, "Football", "Name one truth about your club you refuse to say online."),
    ]

    private static let dares: [Prompt] = [
        d("d-r-1", .rookie, "Gym", "Do 15 air squats while announcing each rep like a stadium DJ."),
        d("d-r-2", .rookie, "Football", "Give a 20-second pre-match pep talk as if this living room is Wembley."),
        d("d-r-3", .rookie, "Team", "Invent a team chant with everyone else’s names and perform it twice."),
        d("d-r-4", .rookie, "Gym", "Hold a 20-second plank and name three sports during it."),
        d("d-r-5", .rookie, "Football", "Mime taking a penalty in slow motion, including the run-up and celebration."),
        d("d-r-6", .rookie, "Basketball", "Do 10 jumping jacks, then freeze in a 'clutch shooter' pose for 5 seconds."),
        d("d-r-7", .rookie, "Mindset", "Say your sports motto like a movie trailer voice for 10 seconds."),
        d("d-r-8", .rookie, "Football", "Commentate the last 15 seconds of an imaginary World Cup final."),
        d("d-r-9", .rookie, "Gym", "Do 10 wall push-ups with perfect form. If you break form, restart."),
        d("d-r-10", .rookie, "Team", "High-five every player and give each one a ridiculous nickname."),
        d("d-r-11", .rookie, "Running", "Jog in place for 25 seconds while shouting split times."),
        d("d-r-12", .rookie, "Football", "Act out a VAR review using only hand signals and outrage."),
        d("d-r-13", .rookie, "Basketball", "Dribble an imaginary ball through your legs 8 times without laughing."),
        d("d-r-14", .rookie, "Gym", "Do 12 lunges (6 each side) and name a champion on every switch."),
        d("d-r-15", .rookie, "Football", "Celebrate like you just scored in stoppage time. Commit fully."),
        d("d-r-16", .rookie, "Team", "Pick a player and coach them for 20 seconds like you are on the sideline."),
        d("d-r-17", .rookie, "Tennis", "Mime a tennis serve, then argue with an invisible umpire."),
        d("d-r-18", .rookie, "Gym", "Do 20 standing calf raises while counting in a commentator accent."),
        d("d-r-19", .rookie, "Football", "Whistle (or hum) a match-start blast, then shout 'KICK OFF!'"),
        d("d-r-20", .rookie, "Mindset", "Give a 15-second interview as if you just won bronze and wanted gold."),
        d("d-r-21", .rookie, "Football", "Do the robot dance as if reviewing an offside decision."),
        d("d-r-22", .rookie, "Gym", "Do 10 chair stands while saying 'legs for days' each rep."),
        d("d-r-23", .rookie, "Basketball", "Mime a free-throw routine and nail an invisible shot."),
        d("d-r-24", .rookie, "Team", "Lead a 10-second group clap in a stadium rhythm."),
        d("d-r-25", .rookie, "Running", "Do butt kicks for 15 seconds, then strike a finish-line pose."),
        d("d-r-26", .rookie, "Football", "Act out diving for a save, then throw an imaginary ball out."),
        d("d-r-27", .rookie, "Gym", "Hold Superman pose on the floor for 15 seconds."),
        d("d-r-28", .rookie, "Basketball", "Do 8 imaginary crossover dribbles, then pull up for a jumper."),
        d("d-r-29", .rookie, "Team", "Give a 10-second scouting report on the person to your left."),
        d("d-r-30", .rookie, "Football", "Mime kissing the badge on your chest three times."),
        d("d-r-31", .rookie, "Tennis", "Call the score of a pretend set out loud like an umpire."),
        d("d-r-32", .rookie, "Gym", "Do 15 arm circles forward, then 15 reverse, like warming up."),
        d("d-r-33", .rookie, "Football", "Reenact a throw-in technique with perfect seriousness."),
        d("d-r-34", .rookie, "Mindset", "Shout your name as if the stadium announcer just called it."),
        d("d-r-35", .rookie, "Basketball", "Defend an invisible player with shuffle steps for 15 seconds."),
        d("d-r-36", .rookie, "Team", "Invent a handshake with the next player and teach the room."),
        d("d-r-37", .rookie, "Football", "Do a 10-second 'tunnel walk' stare at the camera (phone)."),
        d("d-r-38", .rookie, "Gym", "Do 12 side lunges while naming Olympic host cities."),
        d("d-r-39", .rookie, "Football", "Act like you just got a yellow card and plead your case."),
        d("d-r-40", .rookie, "Basketball", "Do 10 high-knee dribbles with an imaginary ball."),
        d("d-r-41", .rookie, "Running", "March in place for 20 seconds counting cadence out loud."),
        d("d-r-42", .rookie, "Team", "Present the group trophy (any object) like a Champions League lift."),
        d("d-r-43", .rookie, "Football", "Mime a bicycle kick and stick the landing pose."),
        d("d-r-44", .rookie, "Gym", "Do 20 seated punches like a fighter’s warm-up."),
        d("d-r-45", .rookie, "Football", "Do an elaborate corner-flag dance for 10 seconds."),
        d("d-r-46", .rookie, "Basketball", "Call your own shot, then mime a three-pointer."),
        d("d-r-47", .rookie, "Mindset", "Give a 12-second locker-room speech about belief."),
        d("d-r-48", .rookie, "Gym", "Do 10 slow squats whispering 'championship' each time."),
        d("d-r-49", .rookie, "Football", "Act out being substituted and clap the crowd sarcastically."),
        d("d-r-50", .rookie, "Team", "Assign positions to everyone in the room in 20 seconds."),
        d("d-r-51", .rookie, "Football", "Mime heading a corner and celebrate the winner."),
        d("d-r-52", .rookie, "Gym", "Hold a 15-second glute bridge and smile at the group."),
        d("d-r-53", .rookie, "Basketball", "Do a spin move and finish with a layup mime."),
        d("d-r-54", .rookie, "Running", "Do grapevine steps left and right for 20 seconds."),
        d("d-r-55", .rookie, "Football", "Pretend to put on shin pads with dramatic flair."),
        d("d-r-56", .rookie, "Team", "Start a wave that must go around the room twice."),
        d("d-r-57", .rookie, "Football", "Do a goalkeeper jump and catch an imaginary cross."),
        d("d-r-58", .rookie, "Gym", "Do 8 push-ups from the knees if needed, proudly."),
        d("d-r-59", .rookie, "Football", "Mime spraying champagne after a title win (no liquid)."),
        d("d-r-60", .rookie, "Basketball", "Do defensive slides side to side for 15 seconds."),
        d("d-r-61", .rookie, "Mindset", "Recite a made-up athlete creed with hand on heart."),
        d("d-r-62", .rookie, "Football", "Act out a coin toss and choose ends with authority."),
        d("d-r-63", .rookie, "Gym", "Do 10 standing toe touches, announcing flexibility lies."),
        d("d-r-64", .rookie, "Football", "Mime a step-over twice, then pretend to nutmeg someone."),
        d("d-r-65", .rookie, "Team", "Compliment every player’s 'engine' in one sentence each."),
        d("d-r-66", .rookie, "Football", "Do a cold weather warm-up dance for 15 seconds."),
        d("d-r-67", .rookie, "Extreme", "Mime surfing a big wave and wipe out safely."),

        d("d-p-1", .pro, "Gym", "Do 20 push-ups. After every 5, shout a different sport."),
        d("d-p-2", .pro, "Football", "Name 8 World Cup host countries in 20 seconds or do 10 burpees."),
        d("d-p-3", .pro, "Team", "Blindfold yourself (or close your eyes) and do 12 squats while the group counts."),
        d("d-p-4", .pro, "Basketball", "Hold a wall sit for 30 seconds and list starting-five positions."),
        d("d-p-5", .pro, "Football", "Re-enact a red-card argument with the next player as the referee."),
        d("d-p-6", .pro, "Gym", "Do 15 jump squats. If you stop, add 5 more."),
        d("d-p-7", .pro, "Running", "High knees for 20 seconds, then freeze and hold a medal-podium pose."),
        d("d-p-8", .pro, "Mindset", "Deliver a furious halftime rant using only sports clichés."),
        d("d-p-9", .pro, "Football", "Keep an imaginary ball in the air for 10 'kick-ups' using your feet and knees."),
        d("d-p-10", .pro, "Gym", "Do a 40-second plank. Smile the entire time or restart."),
        d("d-p-11", .pro, "Team", "Create a 4-move warm-up routine and make the group copy you once."),
        d("d-p-12", .pro, "Basketball", "Call play-by-play for 25 seconds of an imaginary buzzer-beater."),
        d("d-p-13", .pro, "Football", "Do 10 mountain climbers, then kiss an imaginary trophy."),
        d("d-p-14", .pro, "Gym", "Balance on one leg for 20 seconds, switch, then bow to the crowd."),
        d("d-p-15", .pro, "Extreme", "Do 8 burpees and name an extreme sport on each landing."),
        d("d-p-16", .pro, "Team", "Pick a player to 'mark' and shadow their movements for 20 seconds."),
        d("d-p-17", .pro, "Football", "Sing 10 seconds of a famous football chant, then invent one for this group."),
        d("d-p-18", .pro, "Gym", "Do 16 walking lunges across the room announcing 'championship mode'."),
        d("d-p-19", .pro, "Mindset", "Stare down the next player like a tunnel walk, then shake hands like rivals."),
        d("d-p-20", .pro, "Basketball", "Do 20 fast-feet taps and finish with a fadeaway jumper mime."),
        d("d-p-21", .pro, "Football", "Name 6 Ballon d’Or winners in 15 seconds or do 12 squats."),
        d("d-p-22", .pro, "Gym", "Do 25 jumping jacks. Miss a count and restart from 10."),
        d("d-p-23", .pro, "Basketball", "Hold a defensive stance for 25 seconds while trash-talking politely."),
        d("d-p-24", .pro, "Team", "Run a 30-second tactical huddle using a shoe as your whiteboard."),
        d("d-p-25", .pro, "Football", "Mime a perfect free-kick technique, then watch it 'curl in'."),
        d("d-p-26", .pro, "Running", "Do 30 seconds of fast feet, then announce your 'personal best'."),
        d("d-p-27", .pro, "Gym", "Do 12 push-ups and name a muscle group on each one."),
        d("d-p-28", .pro, "Football", "Act out a disputed handball decision with full drama."),
        d("d-p-29", .pro, "Basketball", "Do 15 squat jumps and call 'and-one' on the last."),
        d("d-p-30", .pro, "Team", "Make the group do 10 claps in sync or you do 10 burpees."),
        d("d-p-31", .pro, "Football", "Commentate your own warm-up for 20 seconds in third person."),
        d("d-p-32", .pro, "Gym", "Hold a wall sit for 35 seconds naming Premier League clubs."),
        d("d-p-33", .pro, "Football", "Do 8 burpees, then flash a 'man of the match' smile."),
        d("d-p-34", .pro, "Basketball", "Mime a full-court press for 20 seconds without stopping feet."),
        d("d-p-35", .pro, "Mindset", "Give a 20-second apology interview after a bad miss."),
        d("d-p-36", .pro, "Gym", "Do 18 reverse lunges counting in Spanish or any other language."),
        d("d-p-37", .pro, "Football", "Act out being stretchered off, then miraculously recover."),
        d("d-p-38", .pro, "Team", "Draft a 5-a-side team from people in the room aloud."),
        d("d-p-39", .pro, "Football", "Do a 15-second step-over freestyle combo."),
        d("d-p-40", .pro, "Gym", "Do a 45-second forearm plank or drop and redo once."),
        d("d-p-41", .pro, "Basketball", "Spin an imaginary ball on your finger for 10 seconds."),
        d("d-p-42", .pro, "Football", "Name 7 Champions League winners or hold a 30-second wall sit."),
        d("d-p-43", .pro, "Running", "High knees + arm pumps for 25 seconds like a track final."),
        d("d-p-44", .pro, "Team", "Teach a 3-part celebration the whole group must copy."),
        d("d-p-45", .pro, "Football", "Mime a goal-line clearance with a heroic dive."),
        d("d-p-46", .pro, "Gym", "Do 20 sumo squats while saying 'stronger than last season'."),
        d("d-p-47", .pro, "Mindset", "Recreate a viral sports interview soundbite for 15 seconds."),
        d("d-p-48", .pro, "Basketball", "Do 12 lateral bounds (soft) and stick each landing."),
        d("d-p-49", .pro, "Football", "Do a 20-second manager touchline meltdown (PG)."),
        d("d-p-50", .pro, "Gym", "Complete 10 slow push-ups with a 2-second pause at the bottom."),
        d("d-p-51", .pro, "Team", "Have the group rate your celebration from 1–10 after you perform one."),
        d("d-p-52", .pro, "Football", "Mime taking a corner and whip it 'into the mixer'."),
        d("d-p-53", .pro, "Extreme", "Do 10 burpees shouting a different adventure sport each time."),
        d("d-p-54", .pro, "Basketball", "Defend the doorway like it is the paint for 20 seconds."),
        d("d-p-55", .pro, "Football", "Name 5 stadiums in 10 seconds or do 15 mountain climbers."),
        d("d-p-56", .pro, "Gym", "Do 30-second dead bug (or bicycle core) without laughing."),
        d("d-p-57", .pro, "Football", "Act out a VAR monitor walk, then change your mind twice."),
        d("d-p-58", .pro, "Team", "Pick a mascot dance and perform it for 15 seconds."),
        d("d-p-59", .pro, "Running", "Do 20 seconds of A-skips, then salute the finish line."),
        d("d-p-60", .pro, "Gym", "Do 14 push-ups; the group chooses your tempo (slow or fast)."),
        d("d-p-61", .pro, "Football", "Perform an entire substitution ritual with an invisible board."),
        d("d-p-62", .pro, "Basketball", "Do 25 shadow dribbles then a step-back three mime."),
        d("d-p-63", .pro, "Mindset", "Deliver a 15-second 'believe in the process' speech."),
        d("d-p-64", .pro, "Football", "Do 12 jump squats celebrating each as a different club."),
        d("d-p-65", .pro, "Gym", "Balance in a tree pose for 20 seconds each side."),
        d("d-p-66", .pro, "Team", "Whistle a march and make the group parade once around the room."),
        d("d-p-67", .pro, "Football", "Mime a panenka penalty and sell the cheekiness."),

        d("d-l-1", .legend, "Gym", "Do 25 push-ups. Break form once and the group adds 5 more."),
        d("d-l-2", .legend, "Football", "Name 10 Ballon d’Or winners in 25 seconds or hold a 45-second wall sit."),
        d("d-l-3", .legend, "Team", "Lead the whole group in 15 jumping jacks as their new captain."),
        d("d-l-4", .legend, "Gym", "Hold a wall sit for 45 seconds while answering sports questions from the group."),
        d("d-l-5", .legend, "Football", "Commentate a hat-trick in 30 seconds without repeating a word for 'goal'."),
        d("d-l-6", .legend, "Extreme", "Do 12 burpees. After the last one, roar like you just won the title."),
        d("d-l-7", .legend, "Running", "Sprint in place for 30 seconds at max effort, then take a calm 'press conference'."),
        d("d-l-8", .legend, "Mindset", "Confess your weakest sport skill, then immediately do 20 squats to 'fix it'."),
        d("d-l-9", .legend, "Gym", "Do a 50-second plank. If your hips drop, restart from 20."),
        d("d-l-10", .legend, "Football", "Take 5 imaginary penalties. The group votes save or goal after each one."),
        d("d-l-11", .legend, "Team", "Give every player a 5-second scouting report, brutally honest but fair."),
        d("d-l-12", .legend, "Basketball", "Do 30 mountain climbers, then call the game-winning play."),
        d("d-l-13", .legend, "Football", "Act out extra-time cramp, get 'treated', then sprint back on for 10 seconds."),
        d("d-l-14", .legend, "Gym", "Complete 20 jump squats. Count backwards from 20 like a shot clock."),
        d("d-l-15", .legend, "Mindset", "Do 10 slow push-ups. On each one say a fear you have in competition."),
        d("d-l-16", .legend, "Team", "Invent a last-minute tactical change and explain it with a shoe as a whiteboard."),
        d("d-l-17", .legend, "Extreme", "Hold a hollow-body or dish position for 20 seconds, then celebrate standing up."),
        d("d-l-18", .legend, "Football", "Name a starting XI from any league in 30 seconds or do 15 burpees."),
        d("d-l-19", .legend, "Gym", "Do 3 rounds of: 5 push-ups, 5 squats, 5 lunges. No rest between rounds."),
        d("d-l-20", .legend, "Team", "Crown yourself MVP in a 20-second speech, then let the group boo or cheer."),
        d("d-l-21", .legend, "Football", "Name 12 clubs from 8 different countries in 30 seconds or do 20 squats."),
        d("d-l-22", .legend, "Gym", "Hold a wall sit for 60 seconds. Drop early and the group picks a forfeit exercise."),
        d("d-l-23", .legend, "Basketball", "Do 40 fast-feet taps, then hit five clutch free-throw mimes."),
        d("d-l-24", .legend, "Team", "Make everyone plank for 20 seconds while you give a captain speech."),
        d("d-l-25", .legend, "Football", "Commentate a full 90 seconds of imaginary end-to-end madness."),
        d("d-l-26", .legend, "Gym", "Do 30 push-ups in as few sets as possible. Announce each set break."),
        d("d-l-27", .legend, "Football", "Perform 3 different iconic celebrations back-to-back."),
        d("d-l-28", .legend, "Basketball", "Do a 45-second defensive slide circuit without stopping."),
        d("d-l-29", .legend, "Mindset", "Confess a sports ego moment, then do 25 jumping jacks."),
        d("d-l-30", .legend, "Gym", "Do 25 lunges total while the group tries to make you laugh."),
        d("d-l-31", .legend, "Football", "Name 8 World Cup Golden Boot winners or do a 40-second plank."),
        d("d-l-32", .legend, "Team", "Draft and announce a full starting lineup from this room only."),
        d("d-l-33", .legend, "Football", "Mime a last-minute winner, then do the full team pile-on alone."),
        d("d-l-34", .legend, "Gym", "Do 4 rounds of 8 mountain climbers + 8 squats."),
        d("d-l-35", .legend, "Basketball", "Call 30 seconds of play-by-play while doing high knees."),
        d("d-l-36", .legend, "Football", "Argue both sides of a dive for 20 seconds, then pick a verdict."),
        d("d-l-37", .legend, "Extreme", "Do 15 burpees. Whisper 'legend' on every odd rep."),
        d("d-l-38", .legend, "Team", "Have each player set a mini-challenge; you must attempt the first three."),
        d("d-l-39", .legend, "Gym", "Hold a single-leg wall sit (or assisted) for 20 seconds each side."),
        d("d-l-40", .legend, "Football", "Create a 20-second chant that includes every player’s name."),
        d("d-l-41", .legend, "Basketball", "Do 20 push-ups, then mime a poster dunk on the nearest doorway."),
        d("d-l-42", .legend, "Mindset", "Deliver a retirement speech in 25 seconds, then 'unretire'."),
        d("d-l-43", .legend, "Gym", "Do a 55-second plank. The group may ask 3 trivia questions mid-plank."),
        d("d-l-44", .legend, "Football", "Name 10 stadium nicknames or do 18 burpees."),
        d("d-l-45", .legend, "Team", "Lead a synchronized 20-second warm-up the group must copy perfectly."),
        d("d-l-46", .legend, "Football", "Take an imaginary penalty with eyes closed; group votes the result."),
        d("d-l-47", .legend, "Gym", "Complete 35 air squats. Form breaks = restart from 15."),
        d("d-l-48", .legend, "Basketball", "Do 50 shadow dribbles, then a game-winning fadeaway."),
        d("d-l-49", .legend, "Running", "Sprint in place 20 seconds, jog 10, sprint 20 — no stopping."),
        d("d-l-50", .legend, "Football", "Role-play a post-match handshake line with every player."),
        d("d-l-51", .legend, "Mindset", "Say your biggest sports insecurity, then do 15 burpees."),
        d("d-l-52", .legend, "Gym", "Do 20 slow tempo squats (3 seconds down). No bouncing."),
        d("d-l-53", .legend, "Football", "Invent a new rule for football and pitch it like a FIFA exec."),
        d("d-l-54", .legend, "Team", "Assign a 'man of the match' and justify it in 20 seconds."),
        d("d-l-55", .legend, "Football", "Mime being 2–0 down at half-time, then flip the energy for kickoff."),
        d("d-l-56", .legend, "Extreme", "Do 18 burpees naming a different country each time."),
        d("d-l-57", .legend, "Basketball", "Wall sit 40 seconds while naming 10 NBA franchises."),
        d("d-l-58", .legend, "Gym", "Do max push-ups in 30 seconds. Announce the number proudly."),
        d("d-l-59", .legend, "Football", "Recreate a famous goal celebration without naming whose it is — group guesses."),
        d("d-l-60", .legend, "Team", "Host a 30-second awards show for this room’s weirdest sports energy."),
        d("d-l-61", .legend, "Football", "Do 10 penalties mime; miss 3 on purpose and act devastated."),
        d("d-l-62", .legend, "Gym", "Finish with 3 max-effort rounds: 10 jumping jacks + 5 push-ups."),
        d("d-l-63", .legend, "Mindset", "Stare at the ceiling and whisper a sports goal, then shout it once."),
        d("d-l-64", .legend, "Football", "Build a last-minute corner routine and assign runners aloud."),
        d("d-l-65", .legend, "Team", "Make the group vote on your legacy nickname; you must use it the rest of the game."),
        d("d-l-66", .legend, "Gym", "Hold a hollow hold or boat pose for 25 seconds, then salute."),
    ]

    private static let overtime: [Prompt] = [
        t("ot-t-1", .legend, "Overtime", "If only one person in this room gets a professional contract, who deserves it?"),
        t("ot-t-2", .legend, "Overtime", "What is the sports lie you have told so many times you almost believe it?"),
        t("ot-t-3", .legend, "Overtime", "Which defeat taught you the most — and who in this room still needs that lesson?"),
        t("ot-t-4", .legend, "Overtime", "Who in this room would survive a full preseason first?"),
        t("ot-t-5", .legend, "Overtime", "What is the cruelest honest scouting report you would write about yourself?"),
        t("ot-t-6", .legend, "Overtime", "If tonight’s MVP must be someone else, who is it?"),
        t("ot-t-7", .legend, "Overtime", "What sports standard do you hold others to that you fail yourself?"),
        t("ot-t-8", .legend, "Overtime", "Remembered for one iconic moment or a decade of consistency — pick."),
        d("ot-d-1", .legend, "Overtime", "Do 30 seconds of max-effort fast feet, then immediately name 5 Olympic sports."),
        d("ot-d-2", .legend, "Overtime", "The group picks a safe exercise. You do 20 reps while they chant your name."),
        d("ot-d-3", .legend, "Overtime", "Hold a wall sit until you name 12 football clubs from 12 different countries."),
        d("ot-d-4", .legend, "Overtime", "Do 40 seconds of continuous movement (your choice) while naming Olympic host cities."),
        d("ot-d-5", .legend, "Overtime", "The group picks three safe exercises; do 8 reps of each without rest."),
        d("ot-d-6", .legend, "Overtime", "Hold a wall sit while the group asks yes/no sports questions until 10 answers."),
        d("ot-d-7", .legend, "Overtime", "Lead 20 burpees as a team count — if anyone messes up the count, you restart once."),
        d("ot-d-8", .legend, "Overtime", "Give a 30-second championship speech, then immediately do 15 push-ups."),
    ]
}
